//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrt_01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCrt_01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d4a3f3c881aab460f77db417da3b4658cba2a25f.
        /// </summary>
        internal static string CBApiKey {
            get {
                return ResourceManager.GetString("CBApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBInstaller.zip.
        /// </summary>
        internal static string CbfileName {
            get {
                return ResourceManager.GetString("CbfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cbmas.valvoline.com:8443/api.
        /// </summary>
        internal static string CBMasServer {
            get {
                return ResourceManager.GetString("CBMasServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Scripts\CBInstall\CB_InstallClient.ps1.
        /// </summary>
        internal static string CBPSScriptPathandName {
            get {
                return ResourceManager.GetString("CBPSScriptPathandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0nk3yman9!.
        /// </summary>
        internal static string CBSApwd {
            get {
                return ResourceManager.GetString("CBSApwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorpVal\a424902.
        /// </summary>
        internal static string CBserviceAccount {
            get {
                return ResourceManager.GetString("CBserviceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\nakylexbit201.corp.valvoline.com\ClientInstallers.
        /// </summary>
        internal static string CBSourceServer {
            get {
                return ResourceManager.GetString("CBSourceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAKYLEXCYB205.corp.valvoline.com.
        /// </summary>
        internal static string CBTaskServer {
            get {
                return ResourceManager.GetString("CBTaskServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDEF {
            get {
                object obj = ResourceManager.GetObject("IDEF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDEF2 {
            get {
                object obj = ResourceManager.GetObject("IDEF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lercSetup.msi.
        /// </summary>
        internal static string LERCFileName {
            get {
                return ResourceManager.GetString("LERCFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\nakylexbit201.corp.valvoline.com\ClientInstallers.
        /// </summary>
        internal static string LERCServer {
            get {
                return ResourceManager.GetString("LERCServer", resourceCulture);
            }
        }
    }
}
